services:
  backend:
    build:
      context: ./backend
    container_name: laboratorio-ciberpunk-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: laboratorio-ciberpunk-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
